variables:
  GIT_SUBMODULE_STRATEGY: recursive
  VIVADO_PATH_SH: '/nfs/data41/software/Xilinx/Vivado/${VIVADO_VERSION}/settings64.sh'
  CLANG_TIDY_PATH: '/opt/rh/llvm-toolset-7.0/root/bin/clang-tidy'
  CLANG_TIDY_OPTIONS: '-format-style=file' #-config='' does not work because of the quotes; -header-filter in .clang-tidy
  CLANG_TIDY_COMP_OPTIONS: '-std=c++11 -I../TrackletAlgorithm -I../TestBenches -I/nfs/data41/software/Xilinx/Vivado/2019.2/include'

stages: # ---------------------------------------------------------------------
  - quality-check
  - hls-build
  - topTF-sim_synth
  - check-results

# Job templates ---------------------------------------------------------------
.job_template: &template_base
  tags:
    - xilinx-tools
  before_script:
    - source $VIVADO_PATH_SH

.job_template: &template_quality-check
  tags:
    - xilinx-tools
  stage: quality-check
  before_script:
    # Needed for new tool version
    - source /opt/rh/llvm-toolset-7.0/enable
  script:
    - cd emData
    - ./download.sh
    - cd ../project
    - pwd; ls -la; # Debug
    # Hard coded -config='' because the quotes do not work in the variable
    - ${CLANG_TIDY_PATH} -config='' ${CLANG_TIDY_OPTIONS} ${CLANG_TIDY_FILES} -- ${CLANG_TIDY_COMP_OPTIONS} ${CLANG_TIDY_INCLUDES}

.job_template: &template_hls-build
  <<: *template_base
  stage: hls-build
  script:
    - cd project
    - pwd; ls -la; # Debug
    - vivado_hls -f "script_${PROJ_NAME}.tcl"
  artifacts:
    when: on_success
    name: "$CI_JOB_NAME-$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - ./project/
      - ./emData/
    expire_in: 1 week

.job_template: &template_topTF-sim_synth
  <<: *template_base
  stage: topTF-sim_synth
  script:
    - cd IntegrationTests/ExpTopPRMEMC_Test
    - pwd; ls -la; #debug
    - vivado -mode tcl -source generate_project.tcl
    - md5sum ./output.txt # Output check right after sim
    - vivado -mode tcl -source synth.tcl
    - md5sum ./output.txt # Output check repeat at the end for convenience 
  artifacts:
    when: on_success
    name: "$CI_JOB_NAME-$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - ./IntegrationTests/ExpTopPRMEMC_Test/*.txt
      - ./IntegrationTests/ExpTopPRMEMC_Test/ExpTopPRMEMC_Test/ExpTopPRMEMC_Test.runs/synth_1/*.rpt
    expire_in: 1 week

.job_template: &template_check-results
  <<: *template_base # to get on the correct runner
  stage: check-results
  script:
    - cd IntegrationTests/ExpTopPRMEMC_Test
    - mkdir TextIO
    # Compare HDL sim output with full machtes Mem/Prints
    - ./CompareMemPrintsFW.sh
  artifacts:
    when: on_success
    name: "$CI_JOB_NAME-$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - ./IntegrationTests/ExpTopPRMEMC_Test/TextIO/*.txt
    expire_in: 10 week
    
# Jobs ------------------------------------------------------------------------
# Quality checks ------------
PR-quality-check:
  <<: *template_quality-check
  variables:
    CLANG_TIDY_FILES: '../TestBenches/ProjectionRouter_test.cpp ../TrackletAlgorithm/ProjectionRouterTop.cc'
ME-quality-check:
  <<: *template_quality-check
  variables:
    CLANG_TIDY_FILES: '../TestBenches/MatchEngine_test.cpp ../TrackletAlgorithm/MatchEngine.cc'
MC-quality-check:
  <<: *template_quality-check
  variables:
    CLANG_TIDY_FILES: '../TestBenches/MatchCalculator_test.cpp ../TrackletAlgorithm/MatchCalculatorTop.cc'
# HLS builds ---------------
PR-hls-build:
  <<: *template_hls-build
  variables:
    VIVADO_VERSION: "2019.2"
    PROJ_NAME: "PR"
ME-hls-build:
  <<: *template_hls-build
  variables:
    VIVADO_VERSION: "2019.2"
    PROJ_NAME: "ME"
MC-hls-build:
  <<: *template_hls-build
  variables:
    VIVADO_VERSION: "2019.2"
    PROJ_NAME: "MC"
Testdata-download: # Download needed data files to populate initial memories and compare final memories
  stage: download
  tags:
    - xilinx-tools # To make it run on lnxserver327
  script:
    - cd IntegrationTests/ExpTopPRMEMC_Test/emData
    - source download.sh
  artifacts:
    when: on_success
    name: "$CI_JOB_NAME-$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - ./IntegrationTests/ExpTopPRMEMC_Test/emData
    expire_in: 1 week
topPRMEMC-build:
  <<: *template_topTF-build
# FW sim_synth ---------------
topPRMEMC-sim_synth:
  <<: *template_topTF-sim_synth
  variables:
    VIVADO_VERSION: "2019.2"
# Check FW results ---------------
topPRMEMC-check-results:
  <<: *template_check-results
  variables:
    VIVADO_VERSION: "2019.2" # Vivado not needed but it is parth of the path that is called
