variables:
  GIT_SUBMODULE_STRATEGY: recursive
  VIVADO_PATH_SH: '/nfs/data41/software/Xilinx/Vivado/${VIVADO_VERSION}/settings64.sh'

stages: # ---------------------------------------------------------------------
  - hls-build

# Job templates ---------------------------------------------------------------
.job_template: &template_base
  tags:
    - xilinx-tools
  before_script:
    - source $VIVADO_PATH_SH

.job_template: &template_hls-build
  <<: *template_base
  stage: hls-build
  script:
    - cd ulimit_test
    - pwd; ls -la; # Debug
    - ulimit -a
    - ulimit -S -n 2048
    - ulimit -a
    - vivado_hls -f script_test.tcl

# Jobs ------------------------------------------------------------------------
hls-build:
  <<: *template_hls-build
  variables:
    VIVADO_VERSION: "2019.2"
