source ../../../src/firmware-hls/firmware/cfg/ip_tools.tcl
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/vmrouter_L3PHIB/solution_VMRouterTop_L3PHIB/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/trackBuilder/solution_TrackBuilder_L1L2/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/vmrouter_L4PHIB/solution_VMRouterTop_L4PHIB/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/inputrouter/solution_InputRouterTop_IR_DTC_PS_2_A/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/inputrouter/solution_InputRouterTop_IR_DTC_2S_1_A/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/inputrouter/solution_InputRouterTop_IR_DTC_2S_2_B/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/inputrouter/solution_InputRouterTop_IR_DTC_2S_4_B/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/inputrouter/solution_InputRouterTop_IR_DTC_PS10G_2_A/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/inputrouter/solution_InputRouterTop_IR_DTC_PS10G_3_A/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/inputrouter/solution_InputRouterTop_IR_DTC_PS_1_A/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/inputrouter/solution_InputRouterTop_IR_DTC_PS_2_B/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/inputrouter/solution_InputRouterTop_IR_DTC_2S_1_B/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/inputrouter/solution_InputRouterTop_IR_DTC_2S_2_A/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/inputrouter/solution_InputRouterTop_IR_DTC_2S_3_A/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/inputrouter/solution_InputRouterTop_IR_DTC_2S_4_A/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/inputrouter/solution_InputRouterTop_IR_DTC_PS10G_1_A/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/inputrouter/solution_InputRouterTop_IR_DTC_PS10G_2_B/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/inputrouter/solution_InputRouterTop_IR_DTC_PS10G_3_B/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/vmrouter_L2PHIB/solution_VMRouterTop_L2PHIB/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/trackletengine/solution_TrackletEngine_PS_PS/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/matchengine/solution_MatchEngineTop_L6/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/matchengine/solution_MatchEngineTop_L5/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/matchengine/solution_MatchEngineTop_L3/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/matchengine/solution_MatchEngineTop_L4/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/projrouter/solution_ProjectionRouterTop_L4PHIB/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/projrouter/solution_ProjectionRouterTop_L5PHIB/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/projrouter/solution_ProjectionRouterTop_L6PHIB/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/projrouter/solution_ProjectionRouterTop_L3PHIB/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/vmrouter_L1PHID/solution_VMRouterTop_L1PHID/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/vmrouter_L6PHIB/solution_VMRouterTop_L6PHIB/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/vmrouter_L5PHIB/solution_VMRouterTop_L5PHIB/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/match_calc/solution_MatchCalculator_L6PHIB/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/match_calc/solution_MatchCalculator_L5PHIB/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/match_calc/solution_MatchCalculator_L3PHIB/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/match_calc/solution_MatchCalculator_L4PHIB/impl/ip/component.xml
tool_add_core -level 0 ../../../src/firmware-hls/firmware/cgn/trackletCalculator/solution_TrackletCalculator_L1L2F/impl/ip/component.xml
